### ISSUE TITLE
中文和英文間加入空白

### ISSUE THREAD

**Issue by poychang** [AngularTaiwan/angular.tw#1]
目前中文和英文有些有加空白，有些沒有，個人偏好加空白，各位呢？

有加空白：`充分利用現代 Web 平臺的各種能力，提供 App 式體驗。`

沒有空白：`充分利用現代Web平臺的各種能力，提供App式體驗。`

**Comment by doggy8088** [comment]
建議直接到 https://github.com/angular/angular-cn 發 PR 修正。

記得要以 `aio` 分支為主喔！
