### ISSUE TITLE
Angular 動畫簡介 - 錯別字

### ISSUE THREAD

**Issue by hochun836** [AngularTaiwan/angular.tw#10]
[Angular 動畫簡介](https://angular.tw/guide/animations)
併為 => 並為

如圖
<img width="362" alt="2020-03-26_121206" src="https://user-images.githubusercontent.com/13325100/77609656-827a9480-6f5b-11ea-924e-7e757d6d4ec5.png">

<img width="362" alt="2020-03-26_121217" src="https://user-images.githubusercontent.com/13325100/77609680-96be9180-6f5b-11ea-8bda-b4f4efadf8b1.png">

**Comment by doggy8088** [comment]
已修正！
