### ISSUE TITLE
NgModule 常見問題 以及 Angular 依賴注入的章節，『只』寫成『隻』

### ISSUE THREAD

**Issue by littlehorseboy** [AngularTaiwan/angular.tw#14]
https://angular.tw/guide/ngmodule-faq#when-do-i-add-components-to-entrycomponents

![Image 3](https://user-images.githubusercontent.com/16015679/77743824-9b667100-7053-11ea-8e95-a16e2e23a10a.png)

---

https://angular.tw/guide/dependency-injection#injector-hierarchy-and-service-instances

![Image 4](https://user-images.githubusercontent.com/16015679/77743872-b0430480-7053-11ea-8461-35a1f5d48926.png)

**Comment by doggy8088** [comment]
這個問題已經找到，下一版會修復，修復後會關閉此 Issue，多謝 :)
