### ISSUE TITLE
修訂技術文件頁面的左側選單

### ISSUE THREAD

**Issue by poychang** [AngularTaiwan/angular.tw#3]
[https://angular.tw/docs](https://angular.tw/docs) 左側選單有舊的推廣連結，移除或更新成適合的。

**Comment by jiaming0708** [comment]
![screen shot 2019-02-21 at 13 59 51](https://user-images.githubusercontent.com/8855285/53146947-f9b75980-35e0-11e9-8e73-90aea6d55764.png)
幫補一下圖
建議都拉掉改成我們自己的`FB`、`論壇`就好

**Comment by doggy8088** [comment]
Done!

![image](https://user-images.githubusercontent.com/88981/53192410-59494f80-3649-11e9-9d28-614baf0306b5.png)
