### ISSUE TITLE
首頁的立即開始文字內容

### ISSUE THREAD

**Issue by poychang** [AngularTaiwan/angular.tw#6]
首頁的立即開始文字內容改成

```diff
+ 開始建構你的 Angular 應用程式
- 開始建構你的 Angular 應用
```

![image](https://user-images.githubusercontent.com/4879879/53217308-80783f00-3692-11e9-922b-ed9a4d9bc7e2.png)

**Comment by poychang** [comment]
我覺得開頭的 "開始" 可以拿掉，這個在去 cn 發 PR

**Comment by doggy8088** [comment]
我覺得 `應用` 改成 `應用程式` 也可以到 CN 去發 PR

**Comment by poychang** [comment]
PR of remove "開始" at [angular/angular-cn #390](https://github.com/angular/angular-cn/pull/390)

**Comment by doggy8088** [comment]
@poychang 他們已經合併了，但是文件網站尚未重新發佈，等發佈之後就會自動更新了！

**Comment by doggy8088** [comment]
終於更新囉！ 😃
