### ISSUE TITLE
基本原理的 Observable 章節中些許錯別字

### ISSUE THREAD

**Issue by littlehorseboy** [AngularTaiwan/angular.tw#9]
![Image 1](https://user-images.githubusercontent.com/16015679/77596412-e179e280-6f36-11ea-8d24-dc21d3873a94.png)

展示瞭如何使用 建議改成 展示了如何使用

---

![Image 2](https://user-images.githubusercontent.com/16015679/77596529-36b5f400-6f37-11ea-9d2f-11448a28ef1a.png)

髮布 建議改成 發布

**Comment by doggy8088** [comment]
下次建議留個網址，方便我直接點擊進去，謝啦 👍 

https://angular.tw/guide/observables

**Comment by doggy8088** [comment]
已修正！
